# apiVersion: getambassador.io/v1
# kind: TLSContext
# metadata:
#   name: tls
# spec:
#   hosts: ["*"]
#   secret: tls-cert
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
  selector:
    service: ambassador
---
# apiVersion: getambassador.io/v1
# kind: Module
# metadata:
#   name: ambassador
# spec:
#   config:
#     use_remote_address: false
#     x_forwarded_proto_redirect: true
