name: Docker

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v1

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig:  ${{ secrets.KUBE_CONFIG }}
        id: setcontext
      - uses: azure/k8s-deploy@v1
        with:
          images: 'quay.io/datawire/ambassador:0.85.0'
          manifests: |
            ambassador-rbac.yaml
            ambassador-service.yaml
          namespace: atomic-pocs
